
use std::collections::LinkedList;

use option::TelnetOption;
use negotiation::NegotiationAction;

///
/// Events generated by `Telnet`.
///
#[derive(Debug)]
pub enum TelnetEvent<'a> {
    /// Data received (excluding telnet commands)
    Data(&'a [u8]),
    /// An unrecognized telnet command received
    UnknownIAC(u8),
    /// A telnet negotiation received
    Negotiation(NegotiationAction, TelnetOption),
    /// A telnet subnegotiation data received
    Subnegotiation(TelnetOption, Box<[u8]>),
    /// Read time out
    TimedOut,
    /// No data to read
    NoData,
    /// Error encountered during processing read buffer
    Error(String)
}
